version: "3"
services:
  jupyter:
    container_name: "pycon_jupyter"
    image: "jupyter/scipy-notebook"
    ports:
    - 8888:8888

  superset:
    container_name: "pycon_superset"
    image: "tylerfowler/superset"
    ports:
    - 8088:8088

  # postgres:
  #   container_name: "pycon_postgres"
  #   image: "postgres"
  #   volumes:
  #     - ./pg_volume:/var/lib/postgresql/
  #   ports:
  #   - 5432:5432

  # minio:
  #   container_name: "pycon_minio"
  #   image: "minio"
  #   volumes:
  #     - ./minio_volume:/data
  #   ports:
  #   - 9000:9000
  #   command:
  #     - server /data

  # apistart:
  #   container_name: "pycon_apistart"
  #   build: "apistar"
  #   volumes:
  #     - ./apistar_volume:/usr/src/app
  #   ports:
  #   - 8000:8000
  #   command:
  #     - gunicorn app:app -b 0.0.0.0:8000

  # volumes:
  #   - pg_volume:./pg_volume
  #   - minio_volume:./minio_volume
  #   - apistar_volume:./apistar_volume


